### ISSUE TITLE
pre-pull large images

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#1746]
**USER STORY:**

After publishing large images it would be nice to automatically pull them to the right nodes (iSolve = 2GB, jupyter-samsh = 8 GB). It does otherwise take quite some time for the first guy using it.

The tool we use for syncing is able to read the labels. So maybe we can add additional key-value pairs to the ```sync-workflow.yaml```? As in

```yaml

clusters:
  dalco-staging-production:
    url: registry.osparc.speag.com
    env_user: SC_DALCO_STAGING_PRODUCTION_USER
    env_password: SC_DALCO_STAGING_PRODUCTION_PASSWORD
    vram_nodes: [hostname1, hostname2]
stages:
  - from:
      source: master
      repository: "simcore/services/comp/isolve-gpu"
    to: 
      - destination: dalco-staging-production
        repository: "simcore/services/comp/isolve-gpu"
        tags: ["2.0.1"]
    prepull:
      nodes: vram_nodes
```
