### ISSUE TITLE
Create cookie-cutter for service projects

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#245]
Need means to start reliably and fast a new service for simcore framework.

Create a coockiecutter for simcore's pyservices. Template for python service projects in simcore. Should include:

- [x] basic project skeleton with convened names and layout 
- [x] configuration (related with issue # ??)
- [x] rest api
- [ ] ~session~ not all have a session
- [ ] ~database/model~ not all have a database
- [x] resources
- [x] cli
- This is part of the industrialization process  of osparc dev: child of #196

**Comment by mguidon** [comment]
openapi allows for sth like this:
```
/endpoint
    parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
     get:

      put:
```
i.e. methods share the parameters section. However, we parse this as a method  in `routing.py::_create_default_operation_mapping`
