### ISSUE TITLE
Contraints are not displayed with arrays

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3037]
Array constraint as
```yaml
title: X
type: array
items:
  type: number
  minimum: 0
```
does not show in the port tooltip
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/cd903cfc-b9fd-49ad-a6fe-211303e1e861)

while if the port is a number
```yaml
title: Positive Time
type: number
minimum: 0
x_unit: micro-second
```
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/3763daee-31ac-4493-9ef6-10c3e3eefc8f)
