### ISSUE TITLE
Ensure that hostname length is not greater than 255 chars

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3791]
In the past this string went over the limit in some deploys
```yaml
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}"
```
we need means to check before deploying or truncate names to guarantee

>>  why no task.slot here? if it ever gets replicated (like when rolling out an update) it will conflict if by chance it starts on the same machine

_Originally posted by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/3787#discussion_r1084559353_

@mrnicegyu11 pointed out that this composition might surpass the limit and causes an error difficult to trace (pending adding issue with more details)

The maximum length of a hostname in Linux is typically 255 characters. This limit is specified in the Internet standard for domain names, which defines the maximum length of a fully-qualified domain name (FQDN) to be 255 characters. The hostname is a part of the FQDN, so it must also adhere to this limit.

It's worth to mention that this 255 characters limit is not only for the hostname but also for the FQDN, which includes the domain name. This means that if your domain name is very long, then you may have less space for the hostname.

**Comment by pcrespov** [comment]
Try
```yaml
services:
  serviceName:
    hostname: "{{.Node.Hostname}}-{{.Node.ID}}-{{.Service.Name}}"
    command:
      - "sh"
      - "-c"
      - "echo $(hostname) && sleep infinity"
    environment:
      HOSTNAME: ${HOSTNAME:=`strings.Truncate(fmt.Sprintf("{{.Node.Hostname}}-{{.Node.ID}}-{{.Service.Name}}"), 256)`}
```
