### ISSUE TITLE
OOIL doesn't like exponential notation

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#4790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

I am trying to build a new service and in the metadata I'd like to have:
```
  input_6:
    displayOrder: 6
    label: Relative residual
    description: Minimum acceptable relative residual
    defaultValue: 1.0e-8
    type: ref_contentSchema
    contentSchema: 
      title: Relative residual
      type: number
      minimum: 1.0e-15
      maximum: 1.0e2
```
When validating the schema with OOIL, I get this error:
```
Status: Image is up to date for itisfoundation/service-integration:master-github-latest
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/scu/.venv/lib/python3.10/site-packages/service_integration/commands/me │
│ tadata.py:67 in get_version                                                  │
│                                                                              │
│   64 │   """Prints to output requested version (legacy)"""                   │
│   65 │                                                                       │
│   66 │   # parse and validate                                                │
│ ❱ 67 │   metadata = ServiceDockerData(**yaml.safe_load(metadata_file.read_te │
│   68 │                                                                       │
│   69 │   attrname = target_version.replace("-", "_")                         │
│   70 │   current_version: str = getattr(metadata, attrname)                  │
│                                                                              │
│ ╭────────────────────────────── locals ───────────────────────────────╮      │
│ │  metadata_file = PosixPath('.osparc/metadata.yml')                  │      │
│ │ target_version = <TargetVersionChoices.SEMANTIC_VERSION: 'version'> │      │
│ ╰─────────────────────────────────────────────────────────────────────╯      │
│                                                                              │
│ in pydantic.main.BaseModel.__init__:341                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for ServiceDockerData
inputs -> input_6 -> contentSchema
  Invalid json-schema at maximum: '1.0e2' is not of type 'number' 
(type=value_error)
```
I suspect we don't support exponential notation? 
Json-schemas support that I believe, see [here](https://json-schema.org/understanding-json-schema/reference/numeric.html?highlight=minimum#id5)

### Definition of Done

We allow exponential notation in our service ports
